#!/bin/bash

# Check the number of arguments
if [ $# -eq 0 ]; then
    # No arguments, execute `tree`.
    tree -P "*.java" --prune
else
    # One argument, execute `java`.
    java -cp webpagesaver/bin:webcompresslib/bin "$@"
fi



